


import "./style.css"

export const metadata = {
  title: "Darts ist Toll",
  description: "Generated by Me",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >{children}</body>
    </html>
  );
}
