


import "./css/global.css"
import "./css/reset.css"
import "./css/variables.css"

export const metadata = {
  title: "Darts ist Toll",
  description: "Generated by Me",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <main className="container">
          {children}
       </main>
      </body>
    </html>
  );
}
